In [1]:
import pandas as pd

df = pd.read_csv("owid_climate_data.csv")
df = df.dropna(subset=["CO2 Emissions Per Capita", "Annual Temperature Anomaly"])
df.to_csv('cleaned_owid_climate_data.csv', index=False)
df.head()

,Country Name,Country Code,Year,CO2 Emissions Per Capita,Annual Temperature Anomaly
0,Afghanistan,AFG,1949,0.001992,-2.020418
1,Afghanistan,AFG,1950,0.010837,-2.298886
2,Afghanistan,AFG,1951,0.011625,-1.287201
3,Afghanistan,AFG,1952,0.011468,-1.237078
4,Afghanistan,AFG,1953,0.013123,-1.084867

In [ ]:
def get_country_data(country, start_year, end_year):
    country_data = df[df['Country Name'] == country]
    country_data = country_data[country_data['Year'] >= start_year]
    country_data = country_data[country_data['Year'] <= end_year]
    return country_data

get_country_data('India', 2000, 2020)

,Country Name,Country Code,Year,CO2 Emissions Per Capita,Annual Temperature Anomaly
6145,India,IND,2000,0.932435,-0.224110
6146,India,IND,2001,0.928220,-0.147684
6147,India,IND,2002,0.940360,0.215657
6148,India,IND,2003,0.956066,-0.042418
6149,India,IND,2004,0.998095,0.001837
6150,India,IND,2005,1.034569,-0.076595
6151,India,IND,2006,1.101976,0.174562
6152,India,IND,2007,1.169509,0.052127
6153,India,IND,2008,1.233049,-0.179187
6154,India,IND,2009,1.315532,0.537815
6155,India,IND,2010,1.348904,0.492528
6156,India,IND,2011,1.399205,-0.155027
6157,India,IND,2012,1.506013,-0.045455
6158,India,IND,2013,1.539630,-0.232880
6159,India,IND,2014,1.637111,-0.003478
6160,India,IND,2015,1.682363,0.275207
6161,India,IND,2016,1.752050,0.656726
6162,India,IND,2017,1.784719,0.518033
6163,India,IND,2018,1.886328,0.321343
6164,India,IND,2019,1.881088,0.284416
6165,India,IND,2020,1.726452,-0.003115

In [11]:
filtered = df[(df['Year'] == 2020) & (df['CO2 Emissions Per Capita'] > 10)][['Country Name', 'CO2 Emissions Per Capita', 'Annual Temperature Anomaly']]
filtered

,Country Name,CO2 Emissions Per Capita,Annual Temperature Anomaly
707,Australia,15.506062,0.413426
1033,Bahrain,25.215979,0.544875
1867,Brunei,24.939121,0.488073
2326,Canada,13.795024,0.144869
4502,Faroe Islands,14.426020,0.148138
6985,Kazakhstan,13.113933,0.940694
7230,Kuwait,21.739220,0.725706
7896,Luxembourg,12.806264,1.281792
8578,Mongolia,11.265909,0.466132
9177,New Caledonia,17.981370,0.353113
9813,Oman,15.174401,0.060757
10575,Qatar,36.564110,0.610190
10743,Russia,11.156080,2.247584
11166,Saudi Arabia,19.879406,0.557455
11938,South Korea,11.524341,0.439023
12967,Trinidad and Tobago,23.677786,0.303785
13442,United Arab Emirates,23.006842,0.546586
13610,United States,13.889589,0.681033

In [5]:
yearly_stats = df.groupby('Year')["Annual Temperature Anomaly"].agg(['mean', 'min', 'max'])
display(yearly_stats)

          mean       min       max
Year
1940 -1.624415 -3.825056  0.423903
1941 -1.251653 -3.941369  1.779448
1942 -1.368997 -3.628582  0.683115
1943 -1.021218 -2.985201  1.080043
1944 -1.000902 -2.997106  0.915558
...        ...       ...       ...
2019  0.601391 -0.226331  1.697816
2020  0.580830 -0.231912  2.247584
2021  0.411804 -0.655329  1.511456
2022  0.444629 -0.582847  1.773571
2023  0.862665 -0.266950  1.894608

[84 rows x 3 columns]